INSERT INTO BOARD VALUES (1, 'chiho');
INSERT INTO BOARD VALUES (2, 'free');

INSERT INTO LIST VALUES (1, 'FIRST LIST', 1);
INSERT INTO LIST VALUES (2, 'SECOND LIST', 1);

INSERT INTO CARD VALUES (1, 'FIRST CARD', 'CHIHO', 1);
INSERT INTO CARD VALUES (2, 'SECOND CARD', 'CHIHO', 2);

INSERT INTO USER VALUES ("qwe", "qwe");