DROP TABLE board if EXISTS;
DROP TABLE card if EXISTS;
DROP TABLE comment if EXISTS;
DROP TABLE list if EXISTS;
DROP TABLE user if EXISTS;

CREATE TABLE board (id bigint generated by default as identity, board_name varchar(50) not null, primary key (id))
CREATE TABLE card (card_id bigint generated by default as identity, card_name varchar(70) not null, description varchar(5000), list_listId bigint, primary key (card_id))
CREATE TABLE comment (comment_id bigint generated by default as identity, content varchar(1000) not null, time_stamp timestamp, user_name varchar(100), card_cardId bigint, primary key (comment_id))
CREATE TABLE list (list_id bigint generated by default as identity, list_name varchar(70) not null, board_id bigint, primary key (list_id))
CREATE TABLE user (pid integer generated by default as identity, user_email varchar(30) not null, user_id varchar(30) not null, user_password varchar(100) not null, primary key (pid))

ALTER TABLE card ADD CONSTRAINT fk_card_parent_id FOREIGN KEY (list_listId) REFERENCES list
ALTER TABLE comment ADD CONSTRAINT fk_comment_parent_id FOREIGN KEY (card_cardId) REFERENCES card
ALTER TABLE LIST ADD CONSTRAINT fk_list_parent_id FOREIGN KEY (board_id) REFERENCES board

INSERT INTO BOARD VALUES (1, 'chiho');
INSERT INTO BOARD VALUES (2, 'free');

INSERT INTO LIST VALUES (1, 'FIRST LIST', 1);
INSERT INTO LIST VALUES (2, 'SECOND LIST', 1);

INSERT INTO CARD VALUES (1, 'FIRST CARD', 'CHIHO', 1);
INSERT INTO CARD VALUES (2, 'SECOND CARD', 'CHIHO', 2);

INSERT INTO USER VALUES ("qwe", "qwe");